name: Surge PR Preview - Build Stage

on:
  pull_request:

jobs:
  build-preview:
    runs-on: ubuntu-22.04

    steps:
      - name: checkout PR
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Build fake demo
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          mkdir site
            echo "This is a preview site for <b>PR #${PR_NUMBER}</b>" > site/index.html
      - name: upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: pr-build-dist
          path: public/